# Generated by Django 2.0.6 on 2018-06-11 23:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Classroom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('location', models.CharField(max_length=200)),
                ('capacity', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Classroom_input',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('classroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hcmfront.Classroom')),
            ],
        ),
        migrations.CreateModel(
            name='Classroom_schedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_hour', models.DateTimeField(verbose_name='date published')),
                ('end_hour', models.DateTimeField(verbose_name='date published')),
                ('classroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hcmfront.Classroom')),
            ],
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(verbose_name='date published')),
                ('start_hour', models.DateTimeField(verbose_name='date published')),
                ('end_hour', models.DateTimeField(verbose_name='date published')),
                ('number_of_people', models.IntegerField(default=0)),
                ('classroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hcmfront.Classroom')),
            ],
        ),
        migrations.CreateModel(
            name='Reservation_input',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classroom_input', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hcmfront.Classroom_input')),
                ('reservation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hcmfront.Reservation')),
            ],
        ),
    ]
